# Part 1 - Data Preprocessing

## Importing the Libraries and Dataset

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:,3:13].values

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y = dataset.iloc[:,13].values

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0])

## Encoding Categorical Data

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])

In [10]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

In [12]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [36]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:,1:]

## Train-Test split

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Feature Scaling

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [40]:
X_train = sc.fit_transform(X_train)

In [41]:
X_train.shape

(8000, 11)

In [42]:
X_test = sc.transform(X_test)

In [43]:
X_test.shape

(2000, 11)

# Part 2 - Let's make the Artificial Neural Network!

## Importing the Keras Libraries and packages

In [44]:
import keras
from keras.models import Sequential
from keras.layers import Dense

## Initializing the ANN

In [45]:
classifier = Sequential()

## Adding Layers Manually one by one!

In [46]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))

In [47]:
# Adding the Second hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [48]:
# Adding the output layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

## Compiling the ANN

In [49]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

## Fitting the ANN to the Training set

In [50]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.5146 - acc: 0.7932
Epoch 2/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4174 - acc: 0.8067
Epoch 3/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3899 - acc: 0.8229
Epoch 4/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3691 - acc: 0.8526
Epoch 5/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3562 - acc: 0.8574
Epoch 6/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3505 - acc: 0.8589
Epoch 7/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3472 - acc: 0.8599
Epoch 8/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3458 - acc: 0.8607
Epoch 9/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3441 - acc: 0.8614
Epoch 10/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3431 - acc: 0.8612

# Part 3 - Making Predictions and Evaluating the model

## Predicting the Test set results

In [51]:
y_pred = classifier.predict(X_test)

In [52]:
y_pred

array([[0.03749658],
       [0.01137221],
       [0.10882819],
       ...,
       [0.63614947],
       [0.09426025],
       [0.29695624]], dtype=float32)

In [53]:
y_pred = (y_pred > 0.5)

In [54]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

## Making the Confusion Matrix

In [57]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [58]:
cm

array([[1549,   58],
       [ 218,  175]])

In [59]:
(1549 + 175) / 2000

0.862