# TensorFlow Basic Syntax

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [8]:
print(result)

b'Hello World'


In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [16]:
result

30

In [17]:
const = tf.constant(10)

In [19]:
fill_mat = tf.fill((4,4),10)

In [20]:
myzeros = tf.zeros((4,4))

In [21]:
myones = tf.ones((4,4))

In [22]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [23]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [24]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [25]:
sess = tf.InteractiveSession()

In [29]:
for op in my_ops:
    print(op.eval())
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-1.36787176 -0.82361066  0.15556177 -0.06899691]
 [ 0.10737599  0.67259109 -1.68564034  0.56004918]
 [-2.04880333  0.2942737   0.14146005  1.09508014]
 [-1.45484638  0.9411788   0.45657399 -1.46953821]]


[[ 0.25240219  0.3397392   0.80797803  0.45443881]
 [ 0.68467832  0.82200873  0.81966484  0.57595873]
 [ 0.77965677  0.86743665  0.31902206  0.28368962]
 [ 0.51775789  0.58398843  0.20643616  0.9287132 ]]




# Matrix Multiplication

In [31]:
a = tf.constant([[1,2],[3,4]])

In [32]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [33]:
b = tf.constant([[10],[20]])

In [34]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [35]:
result = tf.matmul(a,b)

In [36]:
sess.run(result)

array([[ 50],
       [110]], dtype=int32)

In [37]:
result.eval()

array([[ 50],
       [110]], dtype=int32)